### PR TITLE
Add ability to specify destination for file

### LINKED ISSUE #38: Allow restoring .bakfiles to locations other than the original

### PR DESCRIPTION
**Pull request by Serene-Arc**
Implements the feature in #38 and also switches a couple things to pathlib in those sections

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
Seems to be working, looks good, and I *think* the spaghetti reason for that `== []` bit has been rectified.

I'm trying to decide if it'd be easier to rebase this onto #52 or the other way around.

**Comment by ChanceNCounter** [comment]
Might want to take a look at what I just pushed and make sure I didn't break things in turn 👅

**Comment by Serene-Arc** [comment]
Looks good to me :)

**Comment by ChanceNCounter** [comment]
In case you continue contributing (thank you!!!) just a heads-up: this will be the last PR directly to `master` so that I never have to ask the above question again =P

The new default target is the `unstable` branch. I'll move trivial PRs *back* to `master` as they occur.

**Comment by ChanceNCounter** [comment]
Ah, the rare "merge all commits..."

**Pull request merged**
