### PR TITLE
Add decorator to check for directories

### LINKED ISSUE #25: Refuse to operate on directories
`bak` is only designed to work on files. It might someday get an option to work on directories, or perhaps a recursive "bak 'em all" method, because recursive dir copies aren't unheard of. In the meantime, however, `bak` should catch `IsADirectoryError`, and output an error instead of crashing.

### PR DESCRIPTION
**Pull request by Serene-Arc**
This is to resolve issue #25 since it will now check each file-name argument passed in and raise an error if it is a directory.

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
I'll give this a thorough pass later this afternoon (GMT-8)

I have given thought to a `bak -r`, though the potential use cases seem limited. Probably OOS for this PR. Better to handle that `IsADirectoryError` for the time being, which this will.

**Comment by Serene-Arc** [comment]
Backing up an entire directory would have very limited use cases and I think would be best served by some kind of tar compression anyway, since that could snowball quite fast

**Comment by ChanceNCounter** [comment]
Apparently now I've introduced conflicts.

**Comment by Serene-Arc** [comment]
That's weird. Well you need the decorator and to remove the requirement for the path to exist in the Click decorator as well.

**Comment by ChanceNCounter** [comment]
Got it. I just picked the wrong order to merge your PRs =P

**Comment by ChanceNCounter** [comment]
I extended the decorator to handle user output, because it seemed more sensible than adding similar print statements to several functions. It's also doing the conversion to pathlib.Path() now. Nice and lightweight.

**Comment by Serene-Arc** [comment]
Ah cool. That's probably the best way to do it and keeps it all in one place if you want to extend the functionality later on.

**Comment by ChanceNCounter** [comment]
Merged, and thanks again!

**Pull request merged**
